// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Topnresponse topnresponse
// swagger:model topnresponse
type Topnresponse struct {

	// next page
	NextPage *MetricRequest `json:"nextPage,omitempty"`

	// top n metrics
	TopNMetrics []*Metric `json:"topNMetrics"`
}

// Validate validates this topnresponse
func (m *Topnresponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNextPage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTopNMetrics(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Topnresponse) validateNextPage(formats strfmt.Registry) error {

	if swag.IsZero(m.NextPage) { // not required
		return nil
	}

	if m.NextPage != nil {
		if err := m.NextPage.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("nextPage")
			}
			return err
		}
	}

	return nil
}

func (m *Topnresponse) validateTopNMetrics(formats strfmt.Registry) error {

	if swag.IsZero(m.TopNMetrics) { // not required
		return nil
	}

	for i := 0; i < len(m.TopNMetrics); i++ {
		if swag.IsZero(m.TopNMetrics[i]) { // not required
			continue
		}

		if m.TopNMetrics[i] != nil {
			if err := m.TopNMetrics[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("topNMetrics" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Topnresponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Topnresponse) UnmarshalBinary(b []byte) error {
	var res Topnresponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
