// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Top N Micorservice
Top N microservice pulls data from different internal service.It expose API's to search/aggregate operation on metrics collected from internal services.


    Schemes:
      http
      https
    Host: localhost
    BasePath: /api/topn
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
