// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Top N Micorservice
Top N microservice expose API's to collect data from various network device.It also expose API's to search/aggregate operation on metrics collected by devices in network


    Schemes:
      http
      https
    Host: localhost
    BasePath: /api/topn
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
