// Code generated by go-swagger; DO NOT EDIT.

package topn_microservice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetV1PullmetricsParams creates a new GetV1PullmetricsParams object
// no default values defined in spec.
func NewGetV1PullmetricsParams() GetV1PullmetricsParams {

	return GetV1PullmetricsParams{}
}

// GetV1PullmetricsParams contains all the bound params for the get v1 pullmetrics operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetV1Pullmetrics
type GetV1PullmetricsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetV1PullmetricsParams() beforehand.
func (o *GetV1PullmetricsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
