// Code generated by go-swagger; DO NOT EDIT.

package topn_microservice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "TopNService/models"
)

// NewPostV1AnalyticsParams creates a new PostV1AnalyticsParams object
// no default values defined in spec.
func NewPostV1AnalyticsParams() PostV1AnalyticsParams {

	return PostV1AnalyticsParams{}
}

// PostV1AnalyticsParams contains all the bound params for the post v1 analytics operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostV1Analytics
type PostV1AnalyticsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Metric Analytic request.
	  In: body
	*/
	MetricAnalyticRequest *models.MetricAnalyticRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostV1AnalyticsParams() beforehand.
func (o *PostV1AnalyticsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.MetricAnalyticRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("metricAnalyticRequest", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.MetricAnalyticRequest = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
