// Code generated by go-swagger; DO NOT EDIT.

package topn_microservice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "TopNService/models"
)

// PostV1GettopnOKCode is the HTTP code returned for type PostV1GettopnOK
const PostV1GettopnOKCode int = 200

/*PostV1GettopnOK Metric request served successfully

swagger:response postV1GettopnOK
*/
type PostV1GettopnOK struct {

	/*
	  In: Body
	*/
	Payload *models.Topnresponse `json:"body,omitempty"`
}

// NewPostV1GettopnOK creates PostV1GettopnOK with default headers values
func NewPostV1GettopnOK() *PostV1GettopnOK {

	return &PostV1GettopnOK{}
}

// WithPayload adds the payload to the post v1 gettopn o k response
func (o *PostV1GettopnOK) WithPayload(payload *models.Topnresponse) *PostV1GettopnOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 gettopn o k response
func (o *PostV1GettopnOK) SetPayload(payload *models.Topnresponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1GettopnOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostV1GettopnBadRequestCode is the HTTP code returned for type PostV1GettopnBadRequest
const PostV1GettopnBadRequestCode int = 400

/*PostV1GettopnBadRequest Bad Request, Unable to parse the metric message.

swagger:response postV1GettopnBadRequest
*/
type PostV1GettopnBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostV1GettopnBadRequest creates PostV1GettopnBadRequest with default headers values
func NewPostV1GettopnBadRequest() *PostV1GettopnBadRequest {

	return &PostV1GettopnBadRequest{}
}

// WithPayload adds the payload to the post v1 gettopn bad request response
func (o *PostV1GettopnBadRequest) WithPayload(payload *models.Error) *PostV1GettopnBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 gettopn bad request response
func (o *PostV1GettopnBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1GettopnBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostV1GettopnInternalServerErrorCode is the HTTP code returned for type PostV1GettopnInternalServerError
const PostV1GettopnInternalServerErrorCode int = 500

/*PostV1GettopnInternalServerError Internal server error

swagger:response postV1GettopnInternalServerError
*/
type PostV1GettopnInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostV1GettopnInternalServerError creates PostV1GettopnInternalServerError with default headers values
func NewPostV1GettopnInternalServerError() *PostV1GettopnInternalServerError {

	return &PostV1GettopnInternalServerError{}
}

// WithPayload adds the payload to the post v1 gettopn internal server error response
func (o *PostV1GettopnInternalServerError) WithPayload(payload *models.Error) *PostV1GettopnInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post v1 gettopn internal server error response
func (o *PostV1GettopnInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostV1GettopnInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
